import type { BodyPart } from './db';

export const BODY_PARTS: BodyPart[] = ['胸', '背中', '脚', '肩', '腕', '体幹', 'その他'];

const BASE_PRESET_EXERCISES: { name: string; bodyPart: BodyPart }[] = [
  // 胸
  { name: 'ベンチプレス', bodyPart: '胸' },
  { name: 'インクラインベンチプレス', bodyPart: '胸' },
  { name: 'ダンベルプレス', bodyPart: '胸' },
  { name: 'インクラインダンベルプレス', bodyPart: '胸' },
  { name: 'ダンベルフライ', bodyPart: '胸' },
  { name: 'ペックフライ', bodyPart: '胸' },
  { name: 'ケーブルクロスオーバー', bodyPart: '胸' },
  { name: 'チェストプレス', bodyPart: '胸' },
  { name: 'ディップス', bodyPart: '胸' },
  { name: 'プッシュアップ', bodyPart: '胸' },
  // 背中
  { name: 'デッドリフト', bodyPart: '背中' },
  { name: '懸垂（チンニング）', bodyPart: '背中' },
  { name: 'ラットプルダウン', bodyPart: '背中' },
  { name: 'ベントオーバーロウ', bodyPart: '背中' },
  { name: 'ダンベルロウ', bodyPart: '背中' },
  { name: 'シーテッドロウ', bodyPart: '背中' },
  { name: 'Tバーロウ', bodyPart: '背中' },
  { name: 'バックエクステンション', bodyPart: '背中' },
  { name: 'シュラッグ', bodyPart: '背中' },
  // 脚
  { name: 'スクワット', bodyPart: '脚' },
  { name: 'レッグプレス', bodyPart: '脚' },
  { name: 'ブルガリアンスクワット', bodyPart: '脚' },
  { name: 'ランジ', bodyPart: '脚' },
  { name: 'レッグエクステンション', bodyPart: '脚' },
  { name: 'レッグカール', bodyPart: '脚' },
  { name: 'ルーマニアンデッドリフト', bodyPart: '脚' },
  { name: 'ヒップスラスト', bodyPart: '脚' },
  { name: 'カーフレイズ', bodyPart: '脚' },
  { name: 'アダクション', bodyPart: '脚' },
  { name: 'アブダクション', bodyPart: '脚' },
  // 肩
  { name: 'オーバーヘッドプレス', bodyPart: '肩' },
  { name: 'ダンベルショルダープレス', bodyPart: '肩' },
  { name: 'サイドレイズ', bodyPart: '肩' },
  { name: 'フロントレイズ', bodyPart: '肩' },
  { name: 'リアレイズ', bodyPart: '肩' },
  { name: 'アップライトロウ', bodyPart: '肩' },
  { name: 'フェイスプル', bodyPart: '肩' },
  // 腕
  { name: 'バーベルカール', bodyPart: '腕' },
  { name: 'ダンベルカール', bodyPart: '腕' },
  { name: 'ハンマーカール', bodyPart: '腕' },
  { name: 'インクラインダンベルカール', bodyPart: '腕' },
  { name: 'ケーブルカール', bodyPart: '腕' },
  { name: 'トライセプスプレスダウン', bodyPart: '腕' },
  { name: 'スカルクラッシャー', bodyPart: '腕' },
  { name: 'ナローベンチプレス', bodyPart: '腕' },
  { name: 'キックバック', bodyPart: '腕' },
  { name: 'リストカール', bodyPart: '腕' },
  // 体幹
  { name: 'アブローラー', bodyPart: '体幹' },
  { name: 'クランチ', bodyPart: '体幹' },
  { name: 'レッグレイズ', bodyPart: '体幹' },
  { name: 'プランク', bodyPart: '体幹' },
  { name: 'ケーブルクランチ', bodyPart: '体幹' },
  { name: 'ハンギングレッグレイズ', bodyPart: '体幹' },
  { name: 'ロシアンツイスト', bodyPart: '体幹' },
];

// 初期ルーティン（種目名で参照し、seed時にIDへ解決する）
export const PRESET_ROUTINES: { name: string; exerciseNames: string[] }[] = [
  {
    name: '胸の日',
    exerciseNames: ['ベンチプレス', 'インクラインダンベルプレス', 'ダンベルフライ', 'ケーブルクロスオーバー'],
  },
  {
    name: '背中の日',
    exerciseNames: ['デッドリフト', 'ラットプルダウン', 'ベントオーバーロウ', 'シーテッドロウ'],
  },
  {
    name: '脚の日',
    exerciseNames: ['スクワット', 'レッグプレス', 'レッグカール', 'カーフレイズ'],
  },
  {
    name: '肩・腕の日',
    exerciseNames: ['オーバーヘッドプレス', 'サイドレイズ', 'バーベルカール', 'トライセプスプレスダウン'],
  },
];

// 一般的なジムのマシン/フリーウェイト/ケーブル種目（v3で追加。既存ユーザーにはマイグレーションで反映）
export const EXTRA_EXERCISES: { name: string; bodyPart: BodyPart }[] = [
  // 胸
  { name: 'マシンインクラインチェストプレス', bodyPart: '胸' },
  { name: 'マシンデクラインチェストプレス', bodyPart: '胸' },
  { name: 'スミスマシンベンチプレス', bodyPart: '胸' },
  { name: 'スミスマシンインクラインベンチプレス', bodyPart: '胸' },
  { name: 'スミスマシンデクラインベンチプレス', bodyPart: '胸' },
  { name: 'バーベルデクラインベンチプレス', bodyPart: '胸' },
  { name: 'バーベルプルオーバー', bodyPart: '胸' },
  { name: 'ダンベルプルオーバー', bodyPart: '胸' },
  { name: 'デクラインダンベルプレス', bodyPart: '胸' },
  { name: 'デクラインダンベルフライ', bodyPart: '胸' },
  { name: 'インクラインダンベルフライ', bodyPart: '胸' },
  { name: 'ローケーブルクロスオーバー', bodyPart: '胸' },
  { name: 'ハイケーブルクロスオーバー', bodyPart: '胸' },
  { name: 'ケーブルフライ', bodyPart: '胸' },
  { name: 'インクラインケーブルフライ', bodyPart: '胸' },
  { name: 'シーテッドケーブルチェストプレス', bodyPart: '胸' },
  { name: 'スミスマシンナローグリップベンチプレス', bodyPart: '胸' },
  { name: 'インクラインプッシュアップ', bodyPart: '胸' },
  { name: 'デクラインプッシュアップ', bodyPart: '胸' },
  { name: 'ワイドプッシュアップ', bodyPart: '胸' },
  { name: 'スベンドプレス', bodyPart: '胸' },
  { name: 'フロアプレス', bodyPart: '胸' },
  { name: 'ダンベルフロアプレス', bodyPart: '胸' },
  { name: 'アーチャープッシュアップ', bodyPart: '胸' },
  // 背中
  { name: 'ワイドグリップラットプルダウン', bodyPart: '背中' },
  { name: 'リバースグリップラットプルダウン', bodyPart: '背中' },
  { name: 'ビハインドネックプルダウン', bodyPart: '背中' },
  { name: 'ストレートアームプルダウン', bodyPart: '背中' },
  { name: 'ケーブルプルオーバー', bodyPart: '背中' },
  { name: 'アシストチンニング', bodyPart: '背中' },
  { name: 'マシンロウ', bodyPart: '背中' },
  { name: 'ハイロウ', bodyPart: '背中' },
  { name: 'ロープロウ', bodyPart: '背中' },
  { name: 'インバーテッドロウ', bodyPart: '背中' },
  { name: 'ペンドレイロウ', bodyPart: '背中' },
  { name: 'チェストサポーテッドロウ', bodyPart: '背中' },
  { name: 'ワンハンドケーブルロウ', bodyPart: '背中' },
  { name: 'インクラインダンベルロウ', bodyPart: '背中' },
  { name: 'ラックプル', bodyPart: '背中' },
  { name: 'グッドモーニング', bodyPart: '背中' },
  { name: 'ニュートラルグリッププルダウン', bodyPart: '背中' },
  { name: 'マシンプルオーバー', bodyPart: '背中' },
  // 脚
  { name: 'ハックスクワット', bodyPart: '脚' },
  { name: 'スミスマシンスクワット', bodyPart: '脚' },
  { name: 'フロントスクワット', bodyPart: '脚' },
  { name: 'ゴブレットスクワット', bodyPart: '脚' },
  { name: 'シシースクワット', bodyPart: '脚' },
  { name: 'ステップアップ', bodyPart: '脚' },
  { name: 'ウォーキングランジ', bodyPart: '脚' },
  { name: 'サイドランジ', bodyPart: '脚' },
  { name: 'スティフレッグデッドリフト', bodyPart: '脚' },
  { name: 'グルートハムレイズ', bodyPart: '脚' },
  { name: 'スタンディングカーフレイズ', bodyPart: '脚' },
  { name: 'シーテッドカーフレイズ', bodyPart: '脚' },
  { name: 'レッグプレスカーフレイズ', bodyPart: '脚' },
  { name: 'ドンキーカーフレイズ', bodyPart: '脚' },
  { name: 'グルートキックバック', bodyPart: '脚' },
  { name: 'ケーブルプルスルー', bodyPart: '脚' },
  { name: 'ケーブルキックバック', bodyPart: '脚' },
  { name: 'ピストルスクワット', bodyPart: '脚' },
  { name: 'ナローレッグプレス', bodyPart: '脚' },
  { name: 'ワイドレッグプレス', bodyPart: '脚' },
  { name: 'ペンデュラムスクワット', bodyPart: '脚' },
  { name: 'スレッドプッシュ', bodyPart: '脚' },
  // 肩
  { name: 'マシンショルダープレス', bodyPart: '肩' },
  { name: 'スミスマシンショルダープレス', bodyPart: '肩' },
  { name: 'サイドレイズマシン', bodyPart: '肩' },
  { name: 'リアデルトフライマシン', bodyPart: '肩' },
  { name: 'アーノルドプレス', bodyPart: '肩' },
  { name: 'ビハインドネックプレス', bodyPart: '肩' },
  { name: 'プッシュプレス', bodyPart: '肩' },
  { name: 'ケーブルサイドレイズ', bodyPart: '肩' },
  { name: 'ケーブルフロントレイズ', bodyPart: '肩' },
  { name: 'ケーブルリアレイズ', bodyPart: '肩' },
  { name: 'ライイングサイドレイズ', bodyPart: '肩' },
  { name: 'インクラインサイドレイズ', bodyPart: '肩' },
  { name: 'ベントオーバーリアレイズ', bodyPart: '肩' },
  { name: 'インクラインリアレイズ', bodyPart: '肩' },
  { name: 'ケーブルアップライトロウ', bodyPart: '肩' },
  { name: 'プレートフロントレイズ', bodyPart: '肩' },
  { name: 'ランドマインプレス', bodyPart: '肩' },
  { name: 'パイクプッシュアップ', bodyPart: '肩' },
  { name: 'ハンドスタンドプッシュアップ', bodyPart: '肩' },
  { name: 'ケーブルワンアームショルダープレス', bodyPart: '肩' },
  { name: 'リーニングケーブルサイドレイズ', bodyPart: '肩' },
  { name: 'Yレイズ', bodyPart: '肩' },
  // 腕
  { name: 'プリーチャーカール', bodyPart: '腕' },
  { name: 'スパイダーカール', bodyPart: '腕' },
  { name: 'コンセントレーションカール', bodyPart: '腕' },
  { name: 'リバースカール', bodyPart: '腕' },
  { name: 'マシンカール', bodyPart: '腕' },
  { name: 'ケーブルハンマーカール', bodyPart: '腕' },
  { name: 'ドラッグカール', bodyPart: '腕' },
  { name: 'ゾットマンカール', bodyPart: '腕' },
  { name: 'ライイングトライセプスエクステンション', bodyPart: '腕' },
  { name: 'オーバーヘッドトライセプスエクステンション', bodyPart: '腕' },
  { name: 'ケーブルオーバーヘッドエクステンション', bodyPart: '腕' },
  { name: 'ロープトライセプスプレスダウン', bodyPart: '腕' },
  { name: 'トライセプスエクステンションマシン', bodyPart: '腕' },
  { name: 'ディップスマシン', bodyPart: '腕' },
  { name: 'ベンチディップス', bodyPart: '腕' },
  { name: 'JMプレス', bodyPart: '腕' },
  { name: 'ダイヤモンドプッシュアップ', bodyPart: '腕' },
  { name: 'リバースリストカール', bodyPart: '腕' },
  { name: 'ビハインドザバックリストカール', bodyPart: '腕' },
  { name: 'ケーブルリバースカール', bodyPart: '腕' },
  { name: 'ワンアームケーブルカール', bodyPart: '腕' },
  // 体幹
  { name: 'アブクランチマシン', bodyPart: '体幹' },
  { name: 'トルソローテーション', bodyPart: '体幹' },
  { name: 'ケーブルウッドチョッパー', bodyPart: '体幹' },
  { name: 'ケーブルパロフプレス', bodyPart: '体幹' },
  { name: 'ダンベルサイドベンド', bodyPart: '体幹' },
  { name: 'デクラインシットアップ', bodyPart: '体幹' },
  { name: 'シットアップ', bodyPart: '体幹' },
  { name: 'バイシクルクランチ', bodyPart: '体幹' },
  { name: 'Vアップ', bodyPart: '体幹' },
  { name: 'サイドプランク', bodyPart: '体幹' },
  { name: 'デッドバグ', bodyPart: '体幹' },
  { name: 'バードドッグ', bodyPart: '体幹' },
  { name: 'マウンテンクライマー', bodyPart: '体幹' },
  { name: 'ニートゥチェスト', bodyPart: '体幹' },
  { name: 'ドラゴンフラッグ', bodyPart: '体幹' },
  { name: 'ケーブルトランクツイスト', bodyPart: '体幹' },
  { name: 'メディシンボールツイスト', bodyPart: '体幹' },
  { name: 'ヒールタッチ', bodyPart: '体幹' },
  { name: 'プランクレッグレイズ', bodyPart: '体幹' },
  { name: 'バーベルロールアウト', bodyPart: '体幹' },
  { name: 'ケーブルサイドベンド', bodyPart: '体幹' },
  { name: 'リバースクランチ', bodyPart: '体幹' },
];

export const PRESET_EXERCISES: { name: string; bodyPart: BodyPart }[] = [
  ...BASE_PRESET_EXERCISES,
  ...EXTRA_EXERCISES,
];
